In [ ]:
import numpy as np

goal_x = np.arange(np.pi/4, 11, np.pi/2)
goal_y = 0.2 * goal_x * np.sin(2*goal_x)


print(f'goal_x: {goal_x}\n goal_y: {goal_y}')

In [ ]:
goal_location = np.array([goal_x[0],  goal_y[0]])
print(f"goal_location: {goal_location}")

In [ ]:
import matplotlib.pyplot as plt

In [14]:
def split(x_pos, y_pos, threshold):
    for i in range(len(x_pos) - 1):
        if abs(x_pos[i] - x_pos[i + 1]) > threshold:
            # Split the trajectory at the gap
            split_x = x_pos[:i + 1]
            next_x = x_pos[i + 1:]
            split_y = y_pos[:i + 1]
            next_y = y_pos[i + 1:]
            return split_x, split_y, next_x, next_y

    # If no gap is found, return the full trajectory as one segment
    return x_pos, y_pos, [], []


In [15]:
def plot_traj(x_pos, y_pos):
    x_segments = []
    y_segments = []
    threshold = 2  # Define the threshold for splitting trajectories

    # Keep splitting until no gaps are found
    while len(x_pos) > 0:
        x_split, y_split, x_pos, y_pos = split(x_pos, y_pos, threshold)

        # Append the current segment if it’s non-empty
        if len(x_split) > 0:
            x_segments.append(x_split)
            y_segments.append(y_split)

        # Exit if no more points remain
        if len(x_pos) == 0:
            break

    # Plot each segment
    for i in range(len(x_segments)):
        plt.plot(x_segments[i], y_segments[i], label=f'Episode {i + 1}')

    # Add markers for the initial and goal positions
    plt.scatter(0, 0, color='green', marker='o', s=100, label='Initial Position')
    plt.scatter(5, 5, color='red', marker='X', s=100, label='Goal Position')

    # Add labels, title, and legend
    plt.xlabel('X values')
    plt.ylabel('Y values')
    plt.title('Trajectory Plot')
    plt.legend()
    plt.show()


In [ ]:
# Test Case 1: Simple continuous trajectory
x_pos1 = [0, 1, 2, 3, 4, 5]
y_pos1 = [0, 1, 2, 3, 4, 5]
print("Test Case 1: Simple continuous trajectory")
plot_traj(x_pos1, y_pos1)

In [ ]:
# Test Case 2: Trajectory with a gap exceeding the threshold
x_pos2 = [0, 1, 2, 10, 11, 12]
y_pos2 = [0, 1, 2, 10, 11, 12]
print("Test Case 2: Trajectory with a gap exceeding the threshold")
plot_traj(x_pos2, y_pos2)

In [ ]:
# Test Case 3: Multiple gaps in the trajectory
x_pos3 = [0, 1, 2, 10, 11, 20, 21, 22]
y_pos3 = [0, 1, 2, 10, 11, 20, 21, 22]
print("Test Case 3: Multiple gaps in the trajectory")
plot_traj(x_pos3, y_pos3)

In [ ]:
# Test Case 4: Single point trajectory
x_pos4 = [0]
y_pos4 = [0]
print("Test Case 4: Single point trajectory")
plot_traj(x_pos4, y_pos4)

In [ ]:
# Test Case 5: Empty trajectory
x_pos5 = []
y_pos5 = []
print("Test Case 5: Empty trajectory (should handle gracefully)")
plot_traj(x_pos5, y_pos5)

In [ ]:
# Test Case 6: No gaps in a larger trajectory
x_pos6 = list(range(20))
y_pos6 = list(range(20))
print("Test Case 6: No gaps in a larger trajectory")
plot_traj(x_pos6, y_pos6)

In [ ]:
# Test Case 7: Gaps at the start or end
x_pos7 = [10, 11, 12, 0, 1, 2]
y_pos7 = [10, 11, 12, 0, 1, 2]
print("Test Case 7: Gaps at the start or end")
plot_traj(x_pos7, y_pos7)

In [ ]:
import psutil, os

process = psutil.Process(os.getpid())
for lib in process.memory_maps():
    if 'omp' in lib.path.lower():
        print(lib.path)


In [ ]:
import numpy
# import scipy
# import matplotlib

print(numpy.__config__.show())
# print(scipy.__config__.show())
# print(pl.__config__.show())


"C:\Users\user\anaconda3\envs\lr24\Lib\site-packages\autograd\numpy\numpy_wrapper.py"


In [ ]:
[-3.15 -3.15 -3.15 -10 -10 -10 -20 -20 -20 -0.21 0.375 -1.98 -0.21 0.375 -1.98 -0.21 0.375 -1.98 -0.21 0.375 -1.98 -21 -21 -21 -21 -21 -21 -21 -21 -21 -21 -21 -21 -0.01 -0.01 -0.01 -0.01 -10 -10 -6.29 -20 -10 -10 -6.29 -20 -10 -10 -6.29 -20 -10 -10 -6.29 -20 -0.01 -0.359]
[3.15 3.15 3.15 10 10 10 20 20 20 0.21 1.2 -1.16 0.21 1.2 -1.16 0.21 1.2 -1.16 0.21 1.2 -1.16 21 21 21 21 21 21 21 21 21 21 21 21 1.01 1.01 1.01 1.01 10 10 6.29 20 10 10 6.29 20 10 10 6.29 20 10 10 6.29 20 1e+05 0.359]


[-0.01 -0.359 -10 -10 -6.29 -20 -10 -10 -6.29 -20 -10 -10 -6.29 -20 -10 -10 -6.29 -20 -3.15 -3.15 -3.15 -10 -10 -10 -20 -20 -20 -0.21 0.375 -1.98 -0.21 0.375 -1.98 -0.21 0.375 -1.98 -0.21 0.375 -1.98 -21 -21 -21 -21 -21 -21 -21 -21 -21 -21 -21 -21 -0.01 -0.01 -0.01 -0.01]
[1e+05 0.359 10 10 6.29 20 10 10 6.29 20 10 10 6.29 20 10 10 6.29 20 3.15 3.15 3.15 10 10 10 20 20 20 0.21 1.2 -1.16 0.21 1.2 -1.16 0.21 1.2 -1.16 0.21 1.2 -1.16 21 21 21 21 21 21 21 21 21 21 21 21 1.01 1.01 1.01 1.01]

In [1]:
from gym.spaces import Box
import numpy as np

obs_space_1 = Box(
    low=np.array([-3.15, -3.15, -3.15, -10, -10, -10, -20, -20, -20, -0.21, 0.375, -1.98, -0.21, 0.375, -1.98, -0.21, 0.375, -1.98, -0.21, 0.375, -1.98, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -0.01, -0.01, -0.01, -0.01, -10, -10, -6.29, -20, -10, -10, -6.29, -20, -10, -10, -6.29, -20, -10, -10, -6.29, -20]),
    high=np.array([3.15, 3.15, 3.15, 10, 10, 10, 20, 20, 20, 0.21, 1.2, -1.16, 0.21, 1.2, -1.16, 0.21, 1.2, -1.16, 0.21, 1.2, -1.16, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 1.01, 1.01, 1.01, 1.01, 10, 10, 6.29, 20, 10, 10, 6.29, 20, 10, 10, 6.29, 20, 10, 10, 6.29, 20]),
    dtype=np.float32
)

obs_space_2 = Box(
    low=np.array([-3.15, -3.15, -3.15, -10, -10, -10, -20, -20, -20, -0.21, 0.375, -1.98, -0.21, 0.375, -1.98, -0.21, 0.375, -1.98, -0.21, 0.375, -1.98, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -0.01, -0.01, -0.01, -0.01, -10, -10, -6.29, -20, -10, -10, -6.29, -20, -10, -10, -6.29, -20, -10, -10, -6.29, -20]),
    high=np.array([3.15, 3.15, 3.15, 10, 10, 10, 20, 20, 20, 0.21, 1.2, -1.16, 0.21, 1.2, -1.16, 0.21, 1.2, -1.16, 0.21, 1.2, -1.16, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 1.01, 1.01, 1.01, 1.01, 10, 10, 6.29, 20, 10, 10, 6.29, 20, 10, 10, 6.29, 20, 10, 10, 6.29, 20]),
    dtype=np.float32
)

# Compare the two spaces
print("Low bounds equal:", np.array_equal(obs_space_1.low, obs_space_2.low))
print("High bounds equal:", np.array_equal(obs_space_1.high, obs_space_2.high))
print("Shapes equal:", obs_space_1.shape == obs_space_2.shape)
print("Dtypes equal:", obs_space_1.dtype == obs_space_2.dtype)


Low bounds equal: True
High bounds equal: True
Shapes equal: True
Dtypes equal: True


c:\Users\user\anaconda3\envs\lr24\lib\site-packages\gym\logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
